//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace cbimtechTools.com.cbimtech.GetClashList {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClashServiceSoap", Namespace="http://services.cbimtech.com/WebServices/")]
    public partial class ClashService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetClashListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClashDetailListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClashByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddClashOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditClashOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClashStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClashDesciplineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClashErrorTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClashMatrixOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClashMatrixDefaultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClashService() {
            this.Url = global::cbimtechTools.Properties.Settings.Default.cbimtechTools_com_cbimtech_GetClashList_ClashService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetClashListCompletedEventHandler GetClashListCompleted;
        
        /// <remarks/>
        public event GetClashDetailListCompletedEventHandler GetClashDetailListCompleted;
        
        /// <remarks/>
        public event GetClashByIDCompletedEventHandler GetClashByIDCompleted;
        
        /// <remarks/>
        public event AddClashCompletedEventHandler AddClashCompleted;
        
        /// <remarks/>
        public event EditClashCompletedEventHandler EditClashCompleted;
        
        /// <remarks/>
        public event GetClashStatusCompletedEventHandler GetClashStatusCompleted;
        
        /// <remarks/>
        public event GetClashDesciplineCompletedEventHandler GetClashDesciplineCompleted;
        
        /// <remarks/>
        public event GetClashErrorTypeCompletedEventHandler GetClashErrorTypeCompleted;
        
        /// <remarks/>
        public event GetClashMatrixCompletedEventHandler GetClashMatrixCompleted;
        
        /// <remarks/>
        public event GetClashMatrixDefaultCompletedEventHandler GetClashMatrixDefaultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/GetClashList", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClashOutput[] GetClashList() {
            object[] results = this.Invoke("GetClashList", new object[0]);
            return ((ClashOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClashListAsync() {
            this.GetClashListAsync(null);
        }
        
        /// <remarks/>
        public void GetClashListAsync(object userState) {
            if ((this.GetClashListOperationCompleted == null)) {
                this.GetClashListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClashListOperationCompleted);
            }
            this.InvokeAsync("GetClashList", new object[0], this.GetClashListOperationCompleted, userState);
        }
        
        private void OnGetClashListOperationCompleted(object arg) {
            if ((this.GetClashListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClashListCompleted(this, new GetClashListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/GetClashDetailList", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClashDetailOutput[] GetClashDetailList() {
            object[] results = this.Invoke("GetClashDetailList", new object[0]);
            return ((ClashDetailOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClashDetailListAsync() {
            this.GetClashDetailListAsync(null);
        }
        
        /// <remarks/>
        public void GetClashDetailListAsync(object userState) {
            if ((this.GetClashDetailListOperationCompleted == null)) {
                this.GetClashDetailListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClashDetailListOperationCompleted);
            }
            this.InvokeAsync("GetClashDetailList", new object[0], this.GetClashDetailListOperationCompleted, userState);
        }
        
        private void OnGetClashDetailListOperationCompleted(object arg) {
            if ((this.GetClashDetailListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClashDetailListCompleted(this, new GetClashDetailListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/GetClashByID", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClashDetailOutput GetClashByID(string _ID) {
            object[] results = this.Invoke("GetClashByID", new object[] {
                        _ID});
            return ((ClashDetailOutput)(results[0]));
        }
        
        /// <remarks/>
        public void GetClashByIDAsync(string _ID) {
            this.GetClashByIDAsync(_ID, null);
        }
        
        /// <remarks/>
        public void GetClashByIDAsync(string _ID, object userState) {
            if ((this.GetClashByIDOperationCompleted == null)) {
                this.GetClashByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClashByIDOperationCompleted);
            }
            this.InvokeAsync("GetClashByID", new object[] {
                        _ID}, this.GetClashByIDOperationCompleted, userState);
        }
        
        private void OnGetClashByIDOperationCompleted(object arg) {
            if ((this.GetClashByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClashByIDCompleted(this, new GetClashByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/AddClash", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddClash(ClashInput enity) {
            object[] results = this.Invoke("AddClash", new object[] {
                        enity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddClashAsync(ClashInput enity) {
            this.AddClashAsync(enity, null);
        }
        
        /// <remarks/>
        public void AddClashAsync(ClashInput enity, object userState) {
            if ((this.AddClashOperationCompleted == null)) {
                this.AddClashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddClashOperationCompleted);
            }
            this.InvokeAsync("AddClash", new object[] {
                        enity}, this.AddClashOperationCompleted, userState);
        }
        
        private void OnAddClashOperationCompleted(object arg) {
            if ((this.AddClashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddClashCompleted(this, new AddClashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/EditClash", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EditClash(ClashInput enity) {
            object[] results = this.Invoke("EditClash", new object[] {
                        enity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EditClashAsync(ClashInput enity) {
            this.EditClashAsync(enity, null);
        }
        
        /// <remarks/>
        public void EditClashAsync(ClashInput enity, object userState) {
            if ((this.EditClashOperationCompleted == null)) {
                this.EditClashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditClashOperationCompleted);
            }
            this.InvokeAsync("EditClash", new object[] {
                        enity}, this.EditClashOperationCompleted, userState);
        }
        
        private void OnEditClashOperationCompleted(object arg) {
            if ((this.EditClashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditClashCompleted(this, new EditClashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/GetClashStatus", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetClashStatus() {
            object[] results = this.Invoke("GetClashStatus", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClashStatusAsync() {
            this.GetClashStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetClashStatusAsync(object userState) {
            if ((this.GetClashStatusOperationCompleted == null)) {
                this.GetClashStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClashStatusOperationCompleted);
            }
            this.InvokeAsync("GetClashStatus", new object[0], this.GetClashStatusOperationCompleted, userState);
        }
        
        private void OnGetClashStatusOperationCompleted(object arg) {
            if ((this.GetClashStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClashStatusCompleted(this, new GetClashStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/GetClashDescipline", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetClashDescipline() {
            object[] results = this.Invoke("GetClashDescipline", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClashDesciplineAsync() {
            this.GetClashDesciplineAsync(null);
        }
        
        /// <remarks/>
        public void GetClashDesciplineAsync(object userState) {
            if ((this.GetClashDesciplineOperationCompleted == null)) {
                this.GetClashDesciplineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClashDesciplineOperationCompleted);
            }
            this.InvokeAsync("GetClashDescipline", new object[0], this.GetClashDesciplineOperationCompleted, userState);
        }
        
        private void OnGetClashDesciplineOperationCompleted(object arg) {
            if ((this.GetClashDesciplineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClashDesciplineCompleted(this, new GetClashDesciplineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/GetClashErrorType", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetClashErrorType() {
            object[] results = this.Invoke("GetClashErrorType", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClashErrorTypeAsync() {
            this.GetClashErrorTypeAsync(null);
        }
        
        /// <remarks/>
        public void GetClashErrorTypeAsync(object userState) {
            if ((this.GetClashErrorTypeOperationCompleted == null)) {
                this.GetClashErrorTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClashErrorTypeOperationCompleted);
            }
            this.InvokeAsync("GetClashErrorType", new object[0], this.GetClashErrorTypeOperationCompleted, userState);
        }
        
        private void OnGetClashErrorTypeOperationCompleted(object arg) {
            if ((this.GetClashErrorTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClashErrorTypeCompleted(this, new GetClashErrorTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/GetClashMatrix", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetClashMatrix() {
            object[] results = this.Invoke("GetClashMatrix", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClashMatrixAsync() {
            this.GetClashMatrixAsync(null);
        }
        
        /// <remarks/>
        public void GetClashMatrixAsync(object userState) {
            if ((this.GetClashMatrixOperationCompleted == null)) {
                this.GetClashMatrixOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClashMatrixOperationCompleted);
            }
            this.InvokeAsync("GetClashMatrix", new object[0], this.GetClashMatrixOperationCompleted, userState);
        }
        
        private void OnGetClashMatrixOperationCompleted(object arg) {
            if ((this.GetClashMatrixCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClashMatrixCompleted(this, new GetClashMatrixCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/GetClashMatrixDefault", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetClashMatrixDefault() {
            object[] results = this.Invoke("GetClashMatrixDefault", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClashMatrixDefaultAsync() {
            this.GetClashMatrixDefaultAsync(null);
        }
        
        /// <remarks/>
        public void GetClashMatrixDefaultAsync(object userState) {
            if ((this.GetClashMatrixDefaultOperationCompleted == null)) {
                this.GetClashMatrixDefaultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClashMatrixDefaultOperationCompleted);
            }
            this.InvokeAsync("GetClashMatrixDefault", new object[0], this.GetClashMatrixDefaultOperationCompleted, userState);
        }
        
        private void OnGetClashMatrixDefaultOperationCompleted(object arg) {
            if ((this.GetClashMatrixDefaultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClashMatrixDefaultCompleted(this, new GetClashMatrixDefaultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.cbimtech.com/WebServices/")]
    public partial class ClashOutput {
        
        private int idField;
        
        private string projectIDField;
        
        private string projectNameField;
        
        private string issueCodeField;
        
        private string issueStatusField;
        
        private string issueDescriptionField;
        
        private int revisionField;
        
        private System.DateTime issueDateField;
        
        private System.DateTime feedbackDateField;
        
        private int isDoneField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectID {
            get {
                return this.projectIDField;
            }
            set {
                this.projectIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        public string IssueCode {
            get {
                return this.issueCodeField;
            }
            set {
                this.issueCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IssueStatus {
            get {
                return this.issueStatusField;
            }
            set {
                this.issueStatusField = value;
            }
        }
        
        /// <remarks/>
        public string IssueDescription {
            get {
                return this.issueDescriptionField;
            }
            set {
                this.issueDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FeedbackDate {
            get {
                return this.feedbackDateField;
            }
            set {
                this.feedbackDateField = value;
            }
        }
        
        /// <remarks/>
        public int isDone {
            get {
                return this.isDoneField;
            }
            set {
                this.isDoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.cbimtech.com/WebServices/")]
    public partial class ClashInput {
        
        private int idField;
        
        private string projectIDField;
        
        private string projectNameField;
        
        private int memberIDField;
        
        private string issueCodeField;
        
        private string issueStatusField;
        
        private int noOfRepeatField;
        
        private string sourcesField;
        
        private string levelField;
        
        private string towerField;
        
        private string gridField;
        
        private string issueDescriptionField;
        
        private string image1Field;
        
        private string image2Field;
        
        private string image3Field;
        
        private string image4Field;
        
        private int revisionField;
        
        private System.DateTime issueDateField;
        
        private string sendToField;
        
        private string cc_toField;
        
        private string fromField;
        
        private string desciplineField;
        
        private string matrix1Field;
        
        private string matrix2Field;
        
        private string priorityField;
        
        private System.DateTime yearField;
        
        private System.DateTime feedbackDateField;
        
        private string layoutTypeField;
        
        private string company_TeamField;
        
        private string constructorSolutionField;
        
        private System.DateTime constructorSolution_DateField;
        
        private string errorTypeField;
        
        private string bIMSolutionField;
        
        private System.DateTime bIMSolution_DateField;
        
        private string clientSolutionField;
        
        private System.DateTime clientSolution_DateField;
        
        private string consultantSolutionField;
        
        private System.DateTime consultantSolution_DateField;
        
        private int isDoneField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectID {
            get {
                return this.projectIDField;
            }
            set {
                this.projectIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        public int MemberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
        
        /// <remarks/>
        public string IssueCode {
            get {
                return this.issueCodeField;
            }
            set {
                this.issueCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IssueStatus {
            get {
                return this.issueStatusField;
            }
            set {
                this.issueStatusField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfRepeat {
            get {
                return this.noOfRepeatField;
            }
            set {
                this.noOfRepeatField = value;
            }
        }
        
        /// <remarks/>
        public string Sources {
            get {
                return this.sourcesField;
            }
            set {
                this.sourcesField = value;
            }
        }
        
        /// <remarks/>
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public string Tower {
            get {
                return this.towerField;
            }
            set {
                this.towerField = value;
            }
        }
        
        /// <remarks/>
        public string Grid {
            get {
                return this.gridField;
            }
            set {
                this.gridField = value;
            }
        }
        
        /// <remarks/>
        public string IssueDescription {
            get {
                return this.issueDescriptionField;
            }
            set {
                this.issueDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Image1 {
            get {
                return this.image1Field;
            }
            set {
                this.image1Field = value;
            }
        }
        
        /// <remarks/>
        public string Image2 {
            get {
                return this.image2Field;
            }
            set {
                this.image2Field = value;
            }
        }
        
        /// <remarks/>
        public string Image3 {
            get {
                return this.image3Field;
            }
            set {
                this.image3Field = value;
            }
        }
        
        /// <remarks/>
        public string Image4 {
            get {
                return this.image4Field;
            }
            set {
                this.image4Field = value;
            }
        }
        
        /// <remarks/>
        public int Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public string SendTo {
            get {
                return this.sendToField;
            }
            set {
                this.sendToField = value;
            }
        }
        
        /// <remarks/>
        public string Cc_to {
            get {
                return this.cc_toField;
            }
            set {
                this.cc_toField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string Descipline {
            get {
                return this.desciplineField;
            }
            set {
                this.desciplineField = value;
            }
        }
        
        /// <remarks/>
        public string Matrix1 {
            get {
                return this.matrix1Field;
            }
            set {
                this.matrix1Field = value;
            }
        }
        
        /// <remarks/>
        public string Matrix2 {
            get {
                return this.matrix2Field;
            }
            set {
                this.matrix2Field = value;
            }
        }
        
        /// <remarks/>
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FeedbackDate {
            get {
                return this.feedbackDateField;
            }
            set {
                this.feedbackDateField = value;
            }
        }
        
        /// <remarks/>
        public string LayoutType {
            get {
                return this.layoutTypeField;
            }
            set {
                this.layoutTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Company_Team {
            get {
                return this.company_TeamField;
            }
            set {
                this.company_TeamField = value;
            }
        }
        
        /// <remarks/>
        public string ConstructorSolution {
            get {
                return this.constructorSolutionField;
            }
            set {
                this.constructorSolutionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ConstructorSolution_Date {
            get {
                return this.constructorSolution_DateField;
            }
            set {
                this.constructorSolution_DateField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        public string BIMSolution {
            get {
                return this.bIMSolutionField;
            }
            set {
                this.bIMSolutionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BIMSolution_Date {
            get {
                return this.bIMSolution_DateField;
            }
            set {
                this.bIMSolution_DateField = value;
            }
        }
        
        /// <remarks/>
        public string ClientSolution {
            get {
                return this.clientSolutionField;
            }
            set {
                this.clientSolutionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ClientSolution_Date {
            get {
                return this.clientSolution_DateField;
            }
            set {
                this.clientSolution_DateField = value;
            }
        }
        
        /// <remarks/>
        public string ConsultantSolution {
            get {
                return this.consultantSolutionField;
            }
            set {
                this.consultantSolutionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ConsultantSolution_Date {
            get {
                return this.consultantSolution_DateField;
            }
            set {
                this.consultantSolution_DateField = value;
            }
        }
        
        /// <remarks/>
        public int isDone {
            get {
                return this.isDoneField;
            }
            set {
                this.isDoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.cbimtech.com/WebServices/")]
    public partial class ClashDetailOutput {
        
        private int idField;
        
        private string projectIDField;
        
        private string projectNameField;
        
        private int memberIDField;
        
        private string issueCodeField;
        
        private string issueStatusField;
        
        private int noOfRepeatField;
        
        private string sourcesField;
        
        private string levelField;
        
        private string towerField;
        
        private string gridField;
        
        private string issueDescriptionField;
        
        private string image1Field;
        
        private string image2Field;
        
        private string image3Field;
        
        private string image4Field;
        
        private int revisionField;
        
        private System.DateTime issueDateField;
        
        private string sendToField;
        
        private string cc_toField;
        
        private string fromField;
        
        private string desciplineField;
        
        private string matrix1Field;
        
        private string matrix2Field;
        
        private string priorityField;
        
        private System.DateTime yearField;
        
        private System.DateTime feedbackDateField;
        
        private string layoutTypeField;
        
        private string company_TeamField;
        
        private string constructorSolutionField;
        
        private System.DateTime constructorSolution_DateField;
        
        private string errorTypeField;
        
        private string bIMSolutionField;
        
        private System.DateTime bIMSolution_DateField;
        
        private string clientSolutionField;
        
        private System.DateTime clientSolution_DateField;
        
        private string consultantSolutionField;
        
        private System.DateTime consultantSolution_DateField;
        
        private int isDoneField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectID {
            get {
                return this.projectIDField;
            }
            set {
                this.projectIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        public int MemberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
        
        /// <remarks/>
        public string IssueCode {
            get {
                return this.issueCodeField;
            }
            set {
                this.issueCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IssueStatus {
            get {
                return this.issueStatusField;
            }
            set {
                this.issueStatusField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfRepeat {
            get {
                return this.noOfRepeatField;
            }
            set {
                this.noOfRepeatField = value;
            }
        }
        
        /// <remarks/>
        public string Sources {
            get {
                return this.sourcesField;
            }
            set {
                this.sourcesField = value;
            }
        }
        
        /// <remarks/>
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public string Tower {
            get {
                return this.towerField;
            }
            set {
                this.towerField = value;
            }
        }
        
        /// <remarks/>
        public string Grid {
            get {
                return this.gridField;
            }
            set {
                this.gridField = value;
            }
        }
        
        /// <remarks/>
        public string IssueDescription {
            get {
                return this.issueDescriptionField;
            }
            set {
                this.issueDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Image1 {
            get {
                return this.image1Field;
            }
            set {
                this.image1Field = value;
            }
        }
        
        /// <remarks/>
        public string Image2 {
            get {
                return this.image2Field;
            }
            set {
                this.image2Field = value;
            }
        }
        
        /// <remarks/>
        public string Image3 {
            get {
                return this.image3Field;
            }
            set {
                this.image3Field = value;
            }
        }
        
        /// <remarks/>
        public string Image4 {
            get {
                return this.image4Field;
            }
            set {
                this.image4Field = value;
            }
        }
        
        /// <remarks/>
        public int Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public string SendTo {
            get {
                return this.sendToField;
            }
            set {
                this.sendToField = value;
            }
        }
        
        /// <remarks/>
        public string Cc_to {
            get {
                return this.cc_toField;
            }
            set {
                this.cc_toField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string Descipline {
            get {
                return this.desciplineField;
            }
            set {
                this.desciplineField = value;
            }
        }
        
        /// <remarks/>
        public string Matrix1 {
            get {
                return this.matrix1Field;
            }
            set {
                this.matrix1Field = value;
            }
        }
        
        /// <remarks/>
        public string Matrix2 {
            get {
                return this.matrix2Field;
            }
            set {
                this.matrix2Field = value;
            }
        }
        
        /// <remarks/>
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FeedbackDate {
            get {
                return this.feedbackDateField;
            }
            set {
                this.feedbackDateField = value;
            }
        }
        
        /// <remarks/>
        public string LayoutType {
            get {
                return this.layoutTypeField;
            }
            set {
                this.layoutTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Company_Team {
            get {
                return this.company_TeamField;
            }
            set {
                this.company_TeamField = value;
            }
        }
        
        /// <remarks/>
        public string ConstructorSolution {
            get {
                return this.constructorSolutionField;
            }
            set {
                this.constructorSolutionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ConstructorSolution_Date {
            get {
                return this.constructorSolution_DateField;
            }
            set {
                this.constructorSolution_DateField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        public string BIMSolution {
            get {
                return this.bIMSolutionField;
            }
            set {
                this.bIMSolutionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BIMSolution_Date {
            get {
                return this.bIMSolution_DateField;
            }
            set {
                this.bIMSolution_DateField = value;
            }
        }
        
        /// <remarks/>
        public string ClientSolution {
            get {
                return this.clientSolutionField;
            }
            set {
                this.clientSolutionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ClientSolution_Date {
            get {
                return this.clientSolution_DateField;
            }
            set {
                this.clientSolution_DateField = value;
            }
        }
        
        /// <remarks/>
        public string ConsultantSolution {
            get {
                return this.consultantSolutionField;
            }
            set {
                this.consultantSolutionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ConsultantSolution_Date {
            get {
                return this.consultantSolution_DateField;
            }
            set {
                this.consultantSolution_DateField = value;
            }
        }
        
        /// <remarks/>
        public int isDone {
            get {
                return this.isDoneField;
            }
            set {
                this.isDoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetClashListCompletedEventHandler(object sender, GetClashListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClashListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClashListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClashOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClashOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetClashDetailListCompletedEventHandler(object sender, GetClashDetailListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClashDetailListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClashDetailListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClashDetailOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClashDetailOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetClashByIDCompletedEventHandler(object sender, GetClashByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClashByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClashByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClashDetailOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClashDetailOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddClashCompletedEventHandler(object sender, AddClashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddClashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddClashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EditClashCompletedEventHandler(object sender, EditClashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditClashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditClashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetClashStatusCompletedEventHandler(object sender, GetClashStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClashStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClashStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetClashDesciplineCompletedEventHandler(object sender, GetClashDesciplineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClashDesciplineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClashDesciplineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetClashErrorTypeCompletedEventHandler(object sender, GetClashErrorTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClashErrorTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClashErrorTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetClashMatrixCompletedEventHandler(object sender, GetClashMatrixCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClashMatrixCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClashMatrixCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetClashMatrixDefaultCompletedEventHandler(object sender, GetClashMatrixDefaultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClashMatrixDefaultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClashMatrixDefaultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591