//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C02a_MemberSkills
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int SkillId { get; set; }
        public Nullable<double> SkillPoint { get; set; }
    
        public virtual C02_BIMstaff C02_BIMstaff { get; set; }
        public virtual C34_SoftwareSkill C34_SoftwareSkill { get; set; }
    }
}
