//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C03_AssignProject
    {
        public int id { get; set; }
        public string ProjectID { get; set; }
        public int MemberId { get; set; }
        public Nullable<System.DateTime> DateAssign { get; set; }
        public Nullable<int> WorkTypeId { get; set; }
        public Nullable<int> ReportTo { get; set; }
        public string Description { get; set; }
    
        public virtual C01_DesignProject C01_DesignProject { get; set; }
        public virtual C02_BIMstaff C02_BIMstaff { get; set; }
        public virtual C16_WorkType C16_WorkType { get; set; }
    }
}
