//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C06_ProjectDetails
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string Zone { get; set; }
        public string Phase { get; set; }
        public string Block { get; set; }
        public string TowerName { get; set; }
        public string LevelCharactorName { get; set; }
        public Nullable<double> LevelHeight { get; set; }
        public Nullable<double> Offset { get; set; }
        public string LevelType { get; set; }
    
        public virtual C01_DesignProject C01_DesignProject { get; set; }
    }
}
