//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C16_WorkType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C16_WorkType()
        {
            this.C03_AssignProject = new HashSet<C03_AssignProject>();
        }
    
        public int WorkID { get; set; }
        public string WorkName { get; set; }
        public Nullable<int> WorkGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C03_AssignProject> C03_AssignProject { get; set; }
        public virtual C16a_WorkTypeGroup C16a_WorkTypeGroup { get; set; }
    }
}
