//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C26_Projects_Tracking
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public Nullable<System.DateTime> Tracking_DateTime { get; set; }
        public string TrackingDetails { get; set; }
        public string Solution { get; set; }
        public string AssignTo { get; set; }
        public Nullable<int> Perior { get; set; }
        public string Status { get; set; }
    
        public virtual C01_DesignProject C01_DesignProject { get; set; }
    }
}
