//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C40_PC_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C40_PC_List()
        {
            this.C41_PC_CheckingReport = new HashSet<C41_PC_CheckingReport>();
            this.C42_PC_LendforUse = new HashSet<C42_PC_LendforUse>();
            this.C44_PCSoftwareReport = new HashSet<C44_PCSoftwareReport>();
        }
    
        public string SohieuMayTinh { get; set; }
        public string CDTCode { get; set; }
        public string ThuongHieuMay { get; set; }
        public string Model { get; set; }
        public string NguoiQuanLyMay { get; set; }
        public string NguoiSuDungHienTai { get; set; }
        public string KichthuocManHinh { get; set; }
        public string VGA { get; set; }
        public string CPU { get; set; }
        public string HDD_SSD { get; set; }
        public string HDD_HDD { get; set; }
        public string RAMslot { get; set; }
        public string RAMslotUsing { get; set; }
        public string DungluongRAM { get; set; }
        public string RAMBus { get; set; }
        public Nullable<int> HoatDong { get; set; }
        public string PhienBanHDH { get; set; }
        public string PCType { get; set; }
        public Nullable<int> Chuot { get; set; }
        public Nullable<int> BoNguon { get; set; }
        public Nullable<int> BaoDungMay { get; set; }
        public string NgayNhanMay { get; set; }
        public Nullable<int> isFree { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C41_PC_CheckingReport> C41_PC_CheckingReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C42_PC_LendforUse> C42_PC_LendforUse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C44_PCSoftwareReport> C44_PCSoftwareReport { get; set; }
    }
}
