//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C41_PC_CheckingReport
    {
        public int ID { get; set; }
        public string SoHieuMayTinh { get; set; }
        public Nullable<System.DateTime> NgayKiemKe { get; set; }
        public string NguoiKiem { get; set; }
        public Nullable<int> HoatDong { get; set; }
        public Nullable<int> Chuot { get; set; }
        public Nullable<int> BoNguon { get; set; }
        public Nullable<int> BaoDungMay { get; set; }
        public string Ghichu { get; set; }
        public string QuanLyMay { get; set; }
    
        public virtual C40_PC_List C40_PC_List { get; set; }
    }
}
