//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C44_PCSoftwareReport
    {
        public int ID { get; set; }
        public string MayTinhID { get; set; }
        public int SoftwareID { get; set; }
        public string DateCheck { get; set; }
        public string BanQuyen { get; set; }
    
        public virtual C40_PC_List C40_PC_List { get; set; }
        public virtual C43_SoftwareList C43_SoftwareList { get; set; }
    }
}
