//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C45_ThucTapSinh
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string NguoiHoTro { get; set; }
        public string ProjectId { get; set; }
        public int ThucTapId { get; set; }
        public string WorkName { get; set; }
        public string CongViecDuocGiao { get; set; }
        public Nullable<System.DateTime> NgayHoanThanhYeucau { get; set; }
        public Nullable<System.DateTime> NgayHoanThanhThucTe { get; set; }
        public string TinhTrangHienTai { get; set; }
        public Nullable<double> PhanTramHoanThanh { get; set; }
        public string DanhGiaKetQua { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> CloseCongViec { get; set; }
    
        public virtual C01_DesignProject C01_DesignProject { get; set; }
        public virtual C02_BIMstaff C02_BIMstaff { get; set; }
    }
}
