//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C47_DrawingManage
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public string Descipline { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public string DrawingNumber { get; set; }
        public string DrawingTitle_EN { get; set; }
        public string DrawingTitle_VN { get; set; }
        public string DrawingLink { get; set; }
        public Nullable<int> Rev { get; set; }
    
        public virtual C01_DesignProject C01_DesignProject { get; set; }
    }
}
