//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C48_VirtualProjects
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string LocationPath { get; set; }
        public string FullPagePath { get; set; }
        public string IconImagePath { get; set; }
    }
}
