//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C96_CostManage
    {
        public int ID { get; set; }
        public int CostID { get; set; }
        public Nullable<System.DateTime> DateTimeSpend { get; set; }
        public Nullable<double> CostValue { get; set; }
        public string Description { get; set; }
    
        public virtual C96_CostManage C96_CostManage1 { get; set; }
        public virtual C96_CostManage C96_CostManage2 { get; set; }
        public virtual C97_CompanyCosts C97_CompanyCosts { get; set; }
    }
}
