//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C98_AppSettings
    {
        public int ID { get; set; }
        public string SettingMainGroup { get; set; }
        public string SettingSubGroup { get; set; }
        public string ItemName { get; set; }
        public string ItemValue { get; set; }
        public string Descriptions { get; set; }
    }
}
