//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbimtechTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C99_Histories
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTimeCreate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ClashID { get; set; }
        public string ProjectID { get; set; }
        public string Scope { get; set; }
        public string Description { get; set; }
    }
}
